# Generated by Django 5.2.10 on 2026-02-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_interviewassessment_learningpath_interviewresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleplaysession',
            name='title',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
    ]
