# Generated by Django 5.2.10 on 2026-03-06 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0003_roleplaysession_title'),
        ('courses', '0005_module_content_alter_module_youtube_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewassessment',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interviewassessment',
            name='selected_skill',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='roleplaysession',
            name='difficulty',
            field=models.CharField(blank=True, default='intermediate', max_length=24),
        ),
        migrations.AddField(
            model_name='roleplaysession',
            name='selected_skill',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='LearningRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_skill', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmap', to='ai_engine.interviewassessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField(default=1)),
                ('stage_title', models.CharField(max_length=255)),
                ('stage_objective', models.TextField()),
                ('learner_actions', models.TextField()),
                ('practical_exercise', models.TextField()),
                ('habit_action', models.TextField()),
                ('course_link', models.URLField(blank=True, default='')),
                ('ai_support_note', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmap_stages', to='courses.course')),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='ai_engine.learningroadmap')),
            ],
            options={
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.AddField(
            model_name='roleplaysession',
            name='roadmap_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roleplay_sessions', to='ai_engine.roadmapstage'),
        ),
        migrations.CreateModel(
            name='UserSkillProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_skill', models.CharField(choices=[('communication', 'Communication'), ('leadership', 'Leadership'), ('emotional intelligence', 'Emotional Intelligence'), ('critical thinking', 'Critical Thinking'), ('time management', 'Time Management'), ('adaptability', 'Adaptability')], max_length=64)),
                ('current_stage_index', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skill_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='roadmapstage',
            constraint=models.UniqueConstraint(fields=('roadmap', 'order_index'), name='unique_stage_order_per_roadmap'),
        ),
    ]
